In [4]:
import pandas as pd
import numpy as np
data={
    'name':['ravi','priya','arjun','meena','kiran'],
    'marks':[45,78,92,60,88],
    'sh':[2,5,8,4,7]
}
df=pd.DataFrame(data)
print(df['marks'].mean())
print(df['marks'].std())
df['marks']=(df['marks']-df['marks'].mean())/df['marks'].std()
print(df)
df['marks']=np.round((df['marks']-df['marks'].min())/(df['marks'].max()-df['marks'].min()),2)
df['sh']=(df['sh']-df['sh'].mean())/df['sh'].std()
df['sh']=np.round((df['sh']-df['sh'].min())/(df['sh'].max()-df['sh'].min()),2)
print(df)

72.6
19.768662069042506
    name     marks  sh
0   ravi -1.396149   2
1  priya  0.273160   5
2  arjun  0.981351   8
3  meena -0.637372   4
4  kiran  0.779011   7
    name  marks    sh
0   ravi   0.00  0.00
1  priya   0.70  0.50
2  arjun   1.00  1.00
3  meena   0.32  0.33
4  kiran   0.91  0.83

In [3]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler=MinMaxScaler()
df['marks_norm_sklearn']=scaler.fit_transform(df[['marks']])
scaler2=StandardScaler()
df['marks_std_sklearn']=scaler2.fit_transform(df[['marks']])
print(df)

    name  marks    sh  marks_norm_sklearn  marks_std_sklearn
0   ravi   0.00  0.00                0.00          -1.562228
1  priya   0.70  0.50                0.70           0.303915
2  arjun   1.00  1.00                1.00           1.103690
3  meena   0.32  0.33                0.32          -0.709134
4  kiran   0.91  0.83                0.91           0.863757

In [17]:
''' 
calculate mean and std 
standardize , round to 2 
noramlize using maxmin
which houses are >avg or < avg
'''
from sklearn.preprocessing import MinMaxScaler,StandardScaler
price = [25,30,35,50,55,60,75] 
df = pd.DataFrame({'price':price})
mean = df['price'].mean() 
std = df['price'].std() 

print(mean,std)
scaler2 = StandardScaler() 
df['price_stnd']=scaler2.fit_transform(df[['price']]).round(2)


scaler_1 = MinMaxScaler() 
df['price_norm'] = scaler_1.fit_transform(df[['price']])
df

47.142857142857146 17.994708216848746

   price  price_stnd  price_norm
0     25       -1.33         0.0
1     30       -1.03         0.1
2     35       -0.73         0.2
3     50        0.17         0.5
4     55        0.47         0.6
5     60        0.77         0.7
6     75        1.67         1.0

In [18]:
rainfall = [120,85,150,200,95,175,110]
df["rainfall"] = rainfall

df["rainfall_std"]=scaler2.fit_transform(df[["rainfall"]])
df["rainfall_norm"]=scaler_1.fit_transform(df[["rainfall"]])
df

   price  price_stnd  price_norm  rainfall  rainfall_std  rainfall_norm
0     25       -1.33         0.0       120     -0.342579       0.304348
1     30       -1.03         0.1        85     -1.226071       0.000000
2     35       -0.73         0.2       150      0.414701       0.565217
3     50        0.17         0.5       200      1.676833       1.000000
4     55        0.47         0.6        95     -0.973645       0.086957
5     60        0.77         0.7       175      1.045767       0.782609
6     75        1.67         1.0       110     -0.595005       0.217391