In [4]:
import pandas as pd 
import numpy as np 
df = pd.DataFrame(np.arange(1,21).reshape(5,4),index=["r1","r2","r3","r4","r5"],columns=["c1","c2","c3","c4"])
df

    c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20

In [8]:
df.tail()

    c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20

In [18]:
df.loc[["r1","r4"],["c2","c3"]]

    c2  c3
r1   2   3
r4  14  15

In [19]:
df.loc["r1":"r4",["c2","c3"]]

    c2  c3
r1   2   3
r2   6   7
r3  10  11
r4  14  15

In [22]:
df.loc["r2": ,["c2","c3"]]

    c2  c3
r2   6   7
r3  10  11
r4  14  15
r5  18  19

In [23]:
#similarly u can do for iloc too

In [24]:
#convert data frame to array 
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])