In [24]:
'''

Exercise 1 Hospital Patient Temperature Analysis Using a 2D NumPy Array
Problem Statement
A hospital records the body temperatures of patients for three consecutive days.
The temperature data is stored in a 2D NumPy array where:
•	Each row represents a patient 
•	Each column represents temperature recorded on a specific day 
•	Given 2D Array
    [98.6, 99.1, 100.2]
    [101.0, 102.5, 101.8]
    [97.9, 98.4, 98.7]
    [100.5, 101.2, 102.0]
days = ["Day1", "Day2", "Day3"]
patients = ["Patient_A", "Patient_B", "Patient_C", "Patient_D"]

Create a Pandas DataFrame from the NumPy array and perform the following tasks:
1.	Display the complete patient temperature DataFrame. 
2.	Display patients whose Day2 temperature is greater than 100°F. 
3.	Calculate the total temperature readings of each patient and store them in a new column called Total_Temp. 
4.	Calculate the average temperature of each patient and store it in a new column called Average_Temp. 
5.	Find the patient with the highest average temperature. 
6.	Add a new column called Health_Status: 
o	"Critical" → if average temperature is greater than or equal to 100°F 
o	"Normal" → otherwise 
7.	Calculate the temperature difference between Day3 and Day1 and store it in a new column called Temp_Difference. 
'''
import numpy as np 
import pandas as pd 
temp = np.array([[98.6, 99.1, 100.2],
    [101.0, 102.5, 101.8],
    [97.9, 98.4, 98.7],
    [100.5, 101.2, 102.0]])
days = np.array(["Day1", "Day2", "Day3"])
patients = np.array(["Patient_A", "Patient_B", "Patient_C", "Patient_D"]) 
d = {days[i]:temp[:,i] for i in range(len(days))}
# print(d)
df = pd.DataFrame(d,index=patients)
print(df)
print()
print(df[df["Day2"]>100])
print()
df["Total"] = df["Day1"]+df["Day2"]+df["Day3"]
print(df)
df["avg temp"] = round(df["Total"]/3,2) 
print()
print(df)
print() 
print(df["avg temp"].idxmax())

df["Health Status"] = df["avg temp"].apply(lambda x:"Critical" if x > 100 else "Normal")
print(df)
print()
df["Temp difference"] = df["Day3"] - df["Day1"]
df

            Day1   Day2   Day3
Patient_A   98.6   99.1  100.2
Patient_B  101.0  102.5  101.8
Patient_C   97.9   98.4   98.7
Patient_D  100.5  101.2  102.0

            Day1   Day2   Day3
Patient_B  101.0  102.5  101.8
Patient_D  100.5  101.2  102.0

            Day1   Day2   Day3  Total
Patient_A   98.6   99.1  100.2  297.9
Patient_B  101.0  102.5  101.8  305.3
Patient_C   97.9   98.4   98.7  295.0
Patient_D  100.5  101.2  102.0  303.7

            Day1   Day2   Day3  Total  avg temp
Patient_A   98.6   99.1  100.2  297.9     99.30
Patient_B  101.0  102.5  101.8  305.3    101.77
Patient_C   97.9   98.4   98.7  295.0     98.33
Patient_D  100.5  101.2  102.0  303.7    101.23

Patient_B
            Day1   Day2   Day3  Total  avg temp Health Status
Patient_A   98.6   99.1  100.2  297.9     99.30        Normal
Patient_B  101.0  102.5  101.8  305.3    101.77      Critical
Patient_C   97.9   98.4   98.7  295.0     98.33        Normal
Patient_D  100.5  101.2  102.0  303.7    101.23      Critical

            Day1   Day2   Day3  Total  avg temp Health Status  Temp difference
Patient_A   98.6   99.1  100.2  297.9     99.30        Normal              1.6
Patient_B  101.0  102.5  101.8  305.3    101.77      Critical              0.8
Patient_C   97.9   98.4   98.7  295.0     98.33        Normal              0.8
Patient_D  100.5  101.2  102.0  303.7    101.23      Critical              1.5

In [3]:
''' 
Exercise 2 : Online Food Delivery Orders Analysis Using Pandas
Problem Statement
A food delivery company tracks the number of weekly orders received from different restaurants.
The order data for three weeks is stored in a 2D NumPy array.
Numpy array
    [450, 520, 610],
    [300, 410, 450],
    [700, 820, 910],
    [500, 540, 600]
# Column names and restaurant names
weeks = ["Week1", "Week2", "Week3"]
restaurants = ["Pizza Hub", "Burger Town", "Spicy Kitchen", "Food Palace"]
Create a Pandas DataFrame from the given data and perform the following tasks:
1.	Display the complete restaurant orders DataFrame. 
2.	Display restaurants with Week2 orders greater than 500. 
3.	Calculate the total orders for each restaurant and store them in a new column called Total_Orders. 
4.	Find the restaurant with the highest total orders. 
5.	Add a new column called Performance: 
o	"Top" → if total orders are greater than or equal to 1500 
o	"Average" → otherwise 
6.	Calculate the growth in orders from Week1 to Week3 and store it in a new column called Growth. 
'''
import numpy as np 
import pandas as pd
data = np.array([[450, 520, 610],
    [300, 410, 450],
    [700, 820, 910],
    [500, 540, 600]])
weeks = np.array(["Week1", "Week2", "Week3"])
restaurants = np.array(["Pizza Hub", "Burger Town", "Spicy Kitchen", "Food Palace"])
orders = pd.DataFrame(data,index=restaurants,columns=weeks)
print(orders)
print()
print(orders[orders["Week2"]>500 ])
print()
orders["Total"] = orders[weeks].sum(axis=1)
print(orders)
print() 
print(orders["Total"].idxmax())
print() 
orders["Perfomance"] = np.where(orders["Total"]>=1500,"Top","Average")
print(orders)
print()
orders["Growth"] = orders["Week3"] - orders["Week1"]
print(orders)

               Week1  Week2  Week3
Pizza Hub        450    520    610
Burger Town      300    410    450
Spicy Kitchen    700    820    910
Food Palace      500    540    600

               Week1  Week2  Week3
Pizza Hub        450    520    610
Spicy Kitchen    700    820    910
Food Palace      500    540    600

               Week1  Week2  Week3  Total
Pizza Hub        450    520    610   1580
Burger Town      300    410    450   1160
Spicy Kitchen    700    820    910   2430
Food Palace      500    540    600   1640

Spicy Kitchen

               Week1  Week2  Week3  Total Perfomance
Pizza Hub        450    520    610   1580        Top
Burger Town      300    410    450   1160    Average
Spicy Kitchen    700    820    910   2430        Top
Food Palace      500    540    600   1640        Top

               Week1  Week2  Week3  Total Perfomance  Growth
Pizza Hub        450    520    610   1580        Top     160
Burger Town      300    410    450   1160    Average     150
Spicy Kitchen    700    820    910   2430        Top     210
Food Palace      500    540    600   1640        Top     100

In [6]:
''' 
Q1. Create a Series from a list

Ravi, Priya, Arjun, Meena, and Kiran scored the following marks in Python exam: 72, 88, 65, 91, 79.

Write code to:

a) Create a Series called python_marks with student names as the index and marks as values.

b) Print the Series.

c) Print only Arjun's mark by using his name as the label.

d) Print only the marks of Priya and Meena together in one statement.

Expected output:

Ravi     72
Priya    88
Arjun    65
Meena    91
Kiran    79
dtype: int64

65

Priya    88
Meena    91
dtype: int64


---


'''
import numpy as np 
import pandas as pd 
names = np.array(["Ravi", "Priya" , "Arjun", "Meena",  "Kiran"])
marks = np.array([72, 88, 65, 91, 79])
ser = pd.Series(marks,index=names)
print(ser)
print(ser["Arjun"])
print(ser[1::2])

Ravi     72
Priya    88
Arjun    65
Meena    91
Kiran    79
dtype: int64
65
Priya    88
Meena    91
dtype: int64

In [12]:
'''
Q2. Series from a dictionary and basic operations

A dictionary stores the number of assignments submitted by each student:

{'Ravi': 8, 'Priya': 10, 'Arjun': 6, 'Meena': 10, 'Kiran': 7}


Write code to:

a) Create a Series submissions from this dictionary.

b) Print the student who submitted the most assignments using idxmax().

c) Print how many students submitted fewer than 8 assignments.

d) Add 1 bonus submission to everyone and print the updated Series.

Expected output:

Priya

2

Ravi      9
Priya    11
Arjun     7
Meena    11
Kiran     8
dtype: int64

'''
d = {'Ravi': 8, 'Priya': 10, 'Arjun': 6, 'Meena': 10, 'Kiran': 7}
ser = pd.Series(d)
print(ser)
print(ser.idxmax())
print(ser[ser<8])
ser[:]+=1
print(ser)

Ravi      8
Priya    10
Arjun     6
Meena    10
Kiran     7
dtype: int64
Priya
Arjun    6
Kiran    7
dtype: int64
Ravi      9
Priya    11
Arjun     7
Meena    11
Kiran     8
dtype: int64

In [20]:
''' 
Q3. Series attributes

Given the Series:
python
attendance = pd.Series([85.5, 92.0, 78.3, 95.1, 88.6],
                       index=['Ravi', 'Priya', 'Arjun', 'Meena', 'Kiran'])


Write code to print each of the following on a separate line:

a) The data type of the Series.

b) The shape of the Series.

c) The total number of elements.

d) All the index labels.

e) All the values as a NumPy array.

Expected output:

float64
(5,)
5
Index(['Ravi', 'Priya', 'Arjun', 'Meena', 'Kiran'], dtype='object')
[85.5 92.  78.3 95.1 88.6]
---

'''
import numpy as np 
import pandas as pd 
attendance = pd.Series([85.5, 92.0, 78.3, 95.1, 88.6],
                       index=['Ravi', 'Priya', 'Arjun', 'Meena', 'Kiran'])
print(attendance.dtypes)
print(attendance.shape)
print(attendance.size)
print(attendance.index)
print(attendance.values)

float64
(5,)
5
Index(['Ravi', 'Priya', 'Arjun', 'Meena', 'Kiran'], dtype='object')
[85.5 92.  78.3 95.1 88.6]

In [34]:
''' 
Q4. Series statistical methods

The internal assessment marks of 5 students are: 34, 28, 40, 22, 36.
Index is: Ravi, Priya, Arjun, Meena, Kiran.

Write code to:

a) Create the Series ia_marks.
b) Print the mean, median, minimum, maximum, and standard deviation (rounded to 2 decimal places).
c) Print the full statistical summary using a single method.

Expected output:

Mean   : 32.0
Median : 34.0
Min    : 22
Max    : 40
Std    : 6.93

count     5.000000
mean     32.000000
std       6.928203
min      22.000000
25%      28.000000
50%      34.000000
75%      36.000000
max      40.000000
dtype: float64

'''
marks = pd.Series([34, 28, 40, 22, 36],index=['Ravi', 'Priya', 'Arjun', 'Meena', 'Kiran'])
# print(marks)
print("Mean:",marks.mean())
print("Median:",marks.median())
print("Min:",marks.min())
print("Max:",marks.max())
print("Std:",round(marks.std(),2))

print(marks.describe())

Mean: 32.0
Median: 34.0
Min: 22
Max: 40
Std: 7.07
count     5.000000
mean     32.000000
std       7.071068
min      22.000000
25%      28.000000
50%      34.000000
75%      36.000000
max      40.000000
dtype: float64

In [8]:
''' 
Q5. Create a DataFrame from a dictionary

Write code to create a DataFrame df with the following data and print it:


Name     RollNo   Maths   Physics   City
Ravi       101      85       76     Hyderabad
Priya      102      92       88     Chennai
Arjun      103      78       82     Bangalore
Meena      104      95       90     Hyderabad
Kiran      105      88       79     Pune


After creating the DataFrame:

a) Print only the first 3 rows.

b) Print the shape, column names, and data types.

Expected output:

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
3  Meena     104     95       90  Hyderabad
4  Kiran     105     88       79       Pune

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore

(5, 5)
Index(['Name', 'RollNo', 'Maths', 'Physics', 'City'], dtype='object')
Name       object
RollNo      int64
Maths       int64
Physics     int64
City       object
dtype: object
---
'''
import numpy as np 
import pandas as pd 
c = np.array(["Name","Roll","Maths","Physics"])

rows = np.array([0,1,2,3,4])
city = np.array(["hyd","chn","blr","hyd","pune"])
# data = np.array([["ravi","priya","arjun","meena","kiran"],[101,102,103,104,105],[85,92,78,95,88],[76,88,82,90,79]])
# info = pd.DataFrame(data,index=c,columns=rows)
d = [["Ravi",101,85,76],["Priya",102,92,88],["arjun",103,78,82],["meena",104,95,90],["kiran",105,88,79]]
info2 = pd.DataFrame(d,index=rows,columns=c)
info2["city"] = city
print(info2)
print(info2.dtypes)
print(info2.shape)
print(info2.columns)

    Name  Roll  Maths  Physics  city
0   Ravi   101     85       76   hyd
1  Priya   102     92       88   chn
2  arjun   103     78       82   blr
3  meena   104     95       90   hyd
4  kiran   105     88       79  pune
Name       object
Roll        int64
Maths       int64
Physics     int64
city       object
dtype: object
(5, 5)
Index(['Name', 'Roll', 'Maths', 'Physics', 'city'], dtype='object')

In [15]:
'''
Q6. Add, compute, and drop columns

Using the same student DataFrame from Q5:

a) Add a new column Total which is the sum of Maths and Physics.

b) Add a new column Average which is Total divided by 2.

c) Add a new column Grade where Average >= 90 gets 'O', Average >= 80 gets 'A', and the rest get 'B'. Use pd.cut or np.select.

d) Drop the Total column.

e) Print the final DataFrame.

Expected output:

    Name  RollNo  Maths  Physics  Average Grade
0   Ravi     101     85       76     80.5     A
1  Priya     102     92       88     90.0     O
2  Arjun     103     78       82     80.0     A
3  Meena     104     95       90     92.5     O
4  Kiran     105     88       79     83.5     A
'''
info2["Total"] = info2["Maths"] + info2["Physics"]
# print(info2) 
info2["Average"]=info2["Total"]/2
# print(info2) 
cond = [
    info2["Average"]>=90,
    info2["Average"]>=80, 
    info2["Average"]<80
]
choices = ["O","A","B"]
info2["Grade"] = np.select(cond,choices,default='Unknown')######################## we can alsos use pd.cut even better
# print(info2)
info2 = info2.drop(columns="Total")#####################
info2

    Name  Roll  Maths  Physics  city  Average Grade
0   Ravi   101     85       76   hyd     80.5     A
1  Priya   102     92       88   chn     90.0     O
2  arjun   103     78       82   blr     80.0     A
3  meena   104     95       90   hyd     92.5     O
4  kiran   105     88       79  pune     83.5     A

In [22]:
'''
Q7. Accessing rows and columns

Using the same student DataFrame from Q5:

a) Print only the Maths column as a Series.

b) Print both Maths and Physics columns as a DataFrame.

c) Print the second row (index 1) using iloc.

d) Print the last 2 rows using tail().

e) Print a random sample of 2 rows using sample() with random_state=42 so results are reproducible.

Expected output:

0    85
1    92
2    78
3    95
4    88
Name: Maths, dtype: int64

   Maths  Physics
0     85       76
1     92       88
2     78       82
3     95       90
4     88       79

Name        Priya
RollNo        102
Maths          92
Physics        88
City      Chennai
Name: 1, dtype: object

    Name  RollNo  Maths  Physics    City
3  Meena     104     95       90  Hyderabad
4  Kiran     105     88       79      Pune
'''
print(info2["Maths"])

print(info2[["Maths","Physics"]])###############

print(info2.iloc[1])

print(info2.tail(2))

0    85
1    92
2    78
3    95
4    88
Name: Maths, dtype: int64
   Maths  Physics
0     85       76
1     92       88
2     78       82
3     95       90
4     88       79
Name       Priya
Roll         102
Maths         92
Physics       88
city         chn
Average     90.0
Grade          O
Name: 1, dtype: object
    Name  Roll  Maths  Physics  city  Average Grade
3  meena   104     95       90   hyd     92.5     O
4  kiran   105     88       79  pune     83.5     A

In [27]:
''' 
Q8. Create a DataFrame from a list of dictionaries

Write code to create a DataFrame from the following list of student records and print it:

python
records = [
    {'Name': 'Ravi',  'Subject': 'Maths',   'Marks': 85, 'Semester': 1},
    {'Name': 'Priya', 'Subject': 'Maths',   'Marks': 92, 'Semester': 1},
    {'Name': 'Ravi',  'Subject': 'Physics', 'Marks': 76, 'Semester': 1},
    {'Name': 'Priya', 'Subject': 'Physics', 'Marks': 88, 'Semester': 1},
    {'Name': 'Arjun', 'Subject': 'Maths',   'Marks': 78, 'Semester': 2},
    {'Name': 'Meena', 'Subject': 'Physics', 'Marks': 90, 'Semester': 2},
]


After creating it:

a) Print the number of rows and columns.

b) Print all unique student names using a single method.

c) Print all unique subjects.

Expected output:

    Name  Subject  Marks  Semester
0   Ravi    Maths     85         1
1  Priya    Maths     92         1
2   Ravi  Physics     76         1
3  Priya  Physics     88         1
4  Arjun    Maths     78         2
5  Meena  Physics     90         2

(6, 4)

['Ravi' 'Priya' 'Arjun' 'Meena']

['Maths' 'Physics']

'''
import numpy as np 
import pandas as pd 
records = [
    {'Name': 'Ravi',  'Subject': 'Maths',   'Marks': 85, 'Semester': 1},
    {'Name': 'Priya', 'Subject': 'Maths',   'Marks': 92, 'Semester': 1},
    {'Name': 'Ravi',  'Subject': 'Physics', 'Marks': 76, 'Semester': 1},
    {'Name': 'Priya', 'Subject': 'Physics', 'Marks': 88, 'Semester': 1},
    {'Name': 'Arjun', 'Subject': 'Maths',   'Marks': 78, 'Semester': 2},
    {'Name': 'Meena', 'Subject': 'Physics', 'Marks': 90, 'Semester': 2},
]
df = pd.DataFrame(records)
print(df)
print(df.shape)
print(df["Name"].unique())
print(df["Subject"].unique())

    Name  Subject  Marks  Semester
0   Ravi    Maths     85         1
1  Priya    Maths     92         1
2   Ravi  Physics     76         1
3  Priya  Physics     88         1
4  Arjun    Maths     78         2
5  Meena  Physics     90         2
(6, 4)
['Ravi' 'Priya' 'Arjun' 'Meena']
['Maths' 'Physics']

In [45]:
''' 
Q9. Set and reset index

Using the student DataFrame from Q5:

a) Set the RollNo column as the row index and print the result.

b) Now access Meena's row using .loc with her RollNo.

c) Reset the index back to default integers and print the first 2 rows.

Expected output:

        Name  Maths  Physics       City
RollNo
101     Ravi     85       76  Hyderabad
102    Priya     92       88    Chennai
103    Arjun     78       82  Bangalore
104    Meena     95       90  Hyderabad
105    Kiran     88       79       Pune

Name        Meena
Maths          95
Physics        90
City    Hyderabad
Name: 104, dtype: object

   RollNo   Name  Maths  Physics       City
0     101   Ravi     85       76  Hyderabad
1     102  Priya     92       88    Chennai


'''
d = {
    "Name":["Ravi","Priya","Arjun","Meena","Kiran"],
    "Maths":[85,92,78,95,88],
    "Physics":[76,88,82,90,79],
    "City":["hyd","chn","blr","hyd","pun"],
    "Roll no":[101,102,103,104,105]
}
stu = pd.DataFrame(d,index=d["Roll no"])
print(stu)
print(stu.loc[104])
stu = pd.DataFrame(d)
stu = stu[["Roll no","Name","Maths","Physics","City"]]
stu

      Name  Maths  Physics City  Roll no
101   Ravi     85       76  hyd      101
102  Priya     92       88  chn      102
103  Arjun     78       82  blr      103
104  Meena     95       90  hyd      104
105  Kiran     88       79  pun      105
Name       Meena
Maths         95
Physics       90
City         hyd
Roll no      104
Name: 104, dtype: object

   Roll no   Name  Maths  Physics City
0      101   Ravi     85       76  hyd
1      102  Priya     92       88  chn
2      103  Arjun     78       82  blr
3      104  Meena     95       90  hyd
4      105  Kiran     88       79  pun

In [46]:
''' 
Q10. Combining Series operations with DataFrame

Write code to do all of the following in sequence:

a) Create the student DataFrame from Q5 (Name, RollNo, Maths, Physics, City).

b) Add a Total column (Maths + Physics).

c) Create a standalone Series called rank with values [3, 1, 5, 1, 4] indexed by the student names (Ravi, Priya, Arjun, Meena, Kiran).
Note Priya and Meena are both rank 1.

d) Add this rank Series as a new column ClassRank to the DataFrame. Use the Name column or set Name as index first to align correctly.

e) Print the final DataFrame sorted by Total in descending order.

Expected output:

    Name  RollNo  Maths  Physics  Total  ClassRank
3  Meena     104     95       90    185          1
1  Priya     102     92       88    180          1
4  Kiran     105     88       79    167          4
0   Ravi     101     85       76    161          3
2  Arjun     103     78       82    160          5

'''
stu["Total"] = stu["Maths"]+stu["Physics"]
print(stu)
rank = pd.Series([3,1,5,1,4], index=d["Name"])
stu["Rank"]=rank.values
stu

   Roll no   Name  Maths  Physics City  Total
0      101   Ravi     85       76  hyd    161
1      102  Priya     92       88  chn    180
2      103  Arjun     78       82  blr    160
3      104  Meena     95       90  hyd    185
4      105  Kiran     88       79  pun    167

   Roll no   Name  Maths  Physics City  Total  Rank
0      101   Ravi     85       76  hyd    161     3
1      102  Priya     92       88  chn    180     1
2      103  Arjun     78       82  blr    160     5
3      104  Meena     95       90  hyd    185     1
4      105  Kiran     88       79  pun    167     4

In [15]:
''' Q11. Read a CSV and inspect it

Assume a file called students.csv exists with the following content:

Name,RollNo,Maths,Physics,City
Ravi,101,85,76,Hyderabad
Priya,102,92,88,Chennai
Arjun,103,78,82,Bangalore
Meena,104,95,90,Hyderabad
Kiran,105,88,79,Pune


Write code to:

a) Read the file into a DataFrame called df.

b) Print the shape.

c) Print the column names.

d) Print the data types of each column.

e) Print the first 3 rows.

Expected output:

(5, 5)

Index(['Name', 'RollNo', 'Maths', 'Physics', 'City'], dtype='object')

Name       object
RollNo      int64
Maths       int64
Physics     int64
City       object
dtype: object

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
'''
print()

In [20]:
import numpy as np 
import pandas as pd
with open("student2.csv","w") as f:
    f.write("""Name,RollNo,Maths,Physics,City
Ravi,101,85,76,Hyderabad
Priya,102,92,88,Chennai
Arjun,103,78,82,Bangalore
Meena,104,95,90,Hyderabad
Kiran,105,88,79,Pune""")
df = pd.read_csv("student2.csv")
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df[:3])
print(df.loc[:2,:"Maths"])

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
3  Meena     104     95       90  Hyderabad
4  Kiran     105     88       79       Pune
(5, 5)
Index(['Name', 'RollNo', 'Maths', 'Physics', 'City'], dtype='object')
Name       object
RollNo      int64
Maths       int64
Physics     int64
City       object
dtype: object
    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
    Name  RollNo  Maths
0   Ravi     101     85
1  Priya     102     92
2  Arjun     103     78

In [22]:
'''
Q12. Read CSV with index column

Using the same students.csv:

a) Read the file again but this time set RollNo as the index column directly in read_csv.

b) Print the DataFrame.

c) Access and print only Priya's row using .loc with her RollNo.

Expected output:

        Name  Maths  Physics       City
RollNo
101     Ravi     85       76  Hyderabad
102    Priya     92       88    Chennai
103    Arjun     78       82  Bangalore
104    Meena     95       90  Hyderabad
105    Kiran     88       79       Pune

Name      Priya
Maths        92
Physics      88
City    Chennai
Name: 102, dtype: object
'''
df = pd.read_csv("student2.csv",index_col="RollNo")
print(df)
print(df.loc[102])

         Name  Maths  Physics       City
RollNo
101      Ravi     85       76  Hyderabad
102     Priya     92       88    Chennai
103     Arjun     78       82  Bangalore
104     Meena     95       90  Hyderabad
105     Kiran     88       79       Pune
Name         Priya
Maths           92
Physics         88
City       Chennai
Name: 102, dtype: object

In [24]:
''' 
Q13. Read only selected columns

Using students.csv:

a) Read only the Name, Maths, and Physics columns using the usecols parameter.

b) Add a Total column.

c) Print the final DataFrame.

Expected output:

    Name  Maths  Physics  Total
0   Ravi     85       76    161
1  Priya     92       88    180
2  Arjun     78       82    160
3  Meena     95       90    185
4  Kiran     88       79    167
'''
df = pd.read_csv("student2.csv",usecols=["Name","Maths","Physics"])
print(df)
df["Total"] = df["Maths"] + df["Physics"]
df

    Name  Maths  Physics
0   Ravi     85       76
1  Priya     92       88
2  Arjun     78       82
3  Meena     95       90
4  Kiran     88       79

    Name  Maths  Physics  Total
0   Ravi     85       76    161
1  Priya     92       88    180
2  Arjun     78       82    160
3  Meena     95       90    185
4  Kiran     88       79    167

In [39]:
''' 
Q14. Read a CSV with missing values

Assume a file students_missing.csv with the following content:

Name,RollNo,Maths,Physics,City
Ravi,101,85,76,Hyderabad
Priya,102,-,88,Chennai
Arjun,103,78,-,Bangalore
Meena,104,95,90,Hyderabad
Kiran,105,88,79,-


Write code to:

a) Read the file treating - as NaN using the na_values parameter.

b) Print how many missing values exist in each column.

c) Print the total number of missing values across the entire DataFrame.

Expected output:

Name       0
RollNo     0
Maths      1
Physics    1
City       1
dtype: int64

3
'''
import numpy as np 
import pandas as pd 
with open("students_missing.csv","w") as f:
    data = '''Name,RollNo,Maths,Physics,City
Ravi,101,85,76,Hyderabad
Priya,102,-,88,Chennai
Arjun,103,78,-,Bangalore
Meena,104,95,90,Hyderabad
Kiran,105,88,79,-'''
    f.write(data)
df = pd.read_csv("students_missing.csv",na_values="-")
print(df.isnull().sum())
print(df.isnull().sum().sum())

Name       0
RollNo     0
Maths      1
Physics    1
City       1
dtype: int64
3

In [45]:
''' 
Q15. Read only first N rows and skip rows

Using students.csv:

a) Read only the first 3 rows using nrows.

b) Print the result.

c) Now write a second read_csv call that skips the first data row (not the header) using skiprows. Print that result.

Expected output for part a:

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore


Expected output for part c (first row Ravi skipped):

    Name  RollNo  Maths  Physics       City
0  Priya     102     92       88    Chennai
1  Arjun     103     78       82  Bangalore
2  Meena     104     95       90  Hyderabad
3  Kiran     105     88       79       Pune

'''
df= pd.read_csv("student2.csv",nrows=3)
print(df)
df2 = pd.read_csv("student2.csv",skiprows=1)
df2

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore

    Ravi  101  85  76  Hyderabad
0  Priya  102  92  88    Chennai
1  Arjun  103  78  82  Bangalore
2  Meena  104  95  90  Hyderabad
3  Kiran  105  88  79       Pune

In [51]:
''' 
Q16. Write a DataFrame to CSV

Write code to:

a) Create the student DataFrame (Name, RollNo, Maths, Physics, City) from Q5.

b) Add a Total column (Maths + Physics).

c) Save it to a file called results.csv without the row index.

d) Read results.csv back in and print it to verify it was saved correctly.

e) Now save it again to results_with_index.csv with the row index included, read it back, and print it to show the difference.

Expected output when reading results.csv:

    Name  RollNo  Maths  Physics       City  Total
0   Ravi     101     85       76  Hyderabad    161
1  Priya     102     92       88    Chennai    180
2  Arjun     103     78       82  Bangalore    160
3  Meena     104     95       90  Hyderabad    185
4  Kiran     105     88       79       Pune    167


Expected output when reading results_with_index.csv:

   Unnamed: 0   Name  RollNo  Maths  Physics       City  Total
0           0   Ravi     101     85       76  Hyderabad    161
1           1  Priya     102     92       88    Chennai    180
...

'''
d = {
    "name":["Ravi","Priya","Arjun","Meena","Kiran"],
    "RollNo":[101,102,103,104,105], 
    "Maths":[85,92,78,95,88], 
    "Physics":[76,88,82,90,79], 
    "City":["hyd","chn","blr","hyd","pun"]
}
df = pd.DataFrame(d)
df["total"] = df["Maths"] + df["Physics"]
print(df)
df.to_csv("Results.csv",index = False)
no_indx = pd.read_csv("Results.csv")
print(no_indx)

df.to_csv("results_with_index.csv",index=True)
with_index = pd.read_csv("results_with_index.csv")
print(with_index)

    name  RollNo  Maths  Physics City  total
0   Ravi     101     85       76  hyd    161
1  Priya     102     92       88  chn    180
2  Arjun     103     78       82  blr    160
3  Meena     104     95       90  hyd    185
4  Kiran     105     88       79  pun    167
    name  RollNo  Maths  Physics City  total
0   Ravi     101     85       76  hyd    161
1  Priya     102     92       88  chn    180
2  Arjun     103     78       82  blr    160
3  Meena     104     95       90  hyd    185
4  Kiran     105     88       79  pun    167
   Unnamed: 0   name  RollNo  Maths  Physics City  total
0           0   Ravi     101     85       76  hyd    161
1           1  Priya     102     92       88  chn    180
2           2  Arjun     103     78       82  blr    160
3           3  Meena     104     95       90  hyd    185
4           4  Kiran     105     88       79  pun    167

In [18]:
'''
Q17. Quick inspection habit after reading

Using students.csv, write a complete file-reading inspection block that prints:

a) The shape of the DataFrame.

b) The data types.

c) The first 5 rows.

d) The count of missing values per column.

e) Basic statistics for numeric columns using a single method.

Write all five steps as a sequence with a print label before each output so it is clear what is being shown.

Expected output:

--- Shape ---
(5, 5)

--- Data Types ---
Name       object
RollNo      int64
Maths       int64
Physics     int64
City       object
dtype: object

--- First 5 Rows ---
    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
3  Meena     104     95       90  Hyderabad
4  Kiran     105     88       79       Pune

--- Missing Values ---
Name       0
RollNo     0
Maths      0
Physics    0
City       0
dtype: int64

--- Statistics ---
       RollNo  Maths    Physics
count     5.0   5.00       5.00
mean    103.0  87.60      83.00
std       1.58   6.58       5.83
min     101.0  78.00      76.00
25%     102.0  85.00      79.00
50%     103.0  88.00      82.00
75%     104.0  92.00      88.00
max     105.0  95.00      90.00

'''
import numpy as np 
import pandas as pd 
df = pd.read_csv("student2.csv")
print(df)
print("---shape---\n",df.shape)
print("---data type---\n",df.dtypes)
print("---1st five---\n",df.head(5))
print("---MIssing Values---\n",df.isnull().sum())
print("---Statistics---\n",df.describe().round(2))

    Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
3  Meena     104     95       90  Hyderabad
4  Kiran     105     88       79       Pune
---shape---
 (5, 5)
---data type---
 Name       object
RollNo      int64
Maths       int64
Physics     int64
City       object
dtype: object
---1st five---
     Name  RollNo  Maths  Physics       City
0   Ravi     101     85       76  Hyderabad
1  Priya     102     92       88    Chennai
2  Arjun     103     78       82  Bangalore
3  Meena     104     95       90  Hyderabad
4  Kiran     105     88       79       Pune
---MIssing Values---
 Name       0
RollNo     0
Maths      0
Physics    0
City       0
dtype: int64
---Statistics---
        RollNo  Maths  Physics
count    5.00   5.00     5.00
mean   103.00  87.60    83.00
std      1.58   6.58     5.92
min    101.00  78.00    76.00
25%    102.00  85.00    79.00
50%    103.00  88.00    82.00
75%    104.00  92.00    88.00
max    105.00  95.00    90.00

In [3]:
''' 
Q18. Read an Excel file and write to CSV

Assume marks.xlsx has a sheet called Semester1 with this data:

Name    Maths   Physics   Chemistry
Ravi      85       76         80
Priya     92       88         91
Arjun     78       82         74
Meena     95       90         93
Kiran     88       79         85


Write code to:

a) Read the Excel file from Semester1 sheet.

b) Print the DataFrame.

c) Add a Total column (sum of all three subjects).

d) Save the result as semester1_results.csv without index.

e) Print a confirmation message: "File saved as semester1_results.csv".

Expected output:

    Name  Maths  Physics  Chemistry
0   Ravi     85       76         80
1  Priya     92       88         91
2  Arjun     78       82         74
3  Meena     95       90         93
4  Kiran     88       79         85

File saved as semester1_results.csv
'''
import numpy as np 
import pandas as pd 

data = {
    "Name":      ["Ravi", "Priya", "Arjun", "Meena", "Kiran"],
    "Maths":     [85, 92, 78, 95, 88],
    "Physics":   [76, 88, 82, 90, 79],
    "Chemistry": [80, 91, 74, 93, 85],
}

df_inp = pd.DataFrame(data)
df_inp.to_excel("marks.xlsx",sheet_name="Semester_1",index=False)

df = pd.read_excel("marks.xlsx",sheet_name="Semester_1")

print(df) 
df["Total"] = df["Maths"] + df["Physics"] +df["Chemistry"]
# df.to_excel("marks.xlsx",sheet_name="semester1_results",index=False) 
df.to_csv("Semester_1_results.csv",index=False)

with pd.ExcelWriter("marks.xlsx",engine="openpyxl",mode="a") as writer:
    df.to_excel(writer ,sheet_name="semester1_results",index=False)

print("file saved as semester_1_results.csv")

    Name  Maths  Physics  Chemistry
0   Ravi     85       76         80
1  Priya     92       88         91
2  Arjun     78       82         74
3  Meena     95       90         93
4  Kiran     88       79         85
file saved as semester_1_results.csv

In [6]:
''' 
Q19. Write multiple DataFrames to separate Excel sheets

You have marks for two semesters:

Semester 1 — Ravi:85, Priya:92, Arjun:78, Meena:95, Kiran:88 (Maths)
Semester 2 — Ravi:90, Priya:88, Arjun:84, Meena:97, Kiran:91 (Maths)

Write code to:

a) Create two DataFrames sem1 and sem2, each with columns Name and Maths.

b) Write both to a single Excel file called all_semesters.xlsx with sheet names Semester1 and Semester2 using ExcelWriter.

c) Read both sheets back in and print them to verify.

Expected output after reading back:

--- Semester 1 ---
    Name  Maths
0   Ravi     85
1  Priya     92
2  Arjun     78
3  Meena     95
4  Kiran     88

--- Semester 2 ---
    Name  Maths
0   Ravi     90
1  Priya     88
2  Arjun     84
3  Meena     97
4  Kiran     91


---

'''
import numpy as np 
import pandas as pd 

sem1df = pd.DataFrame({
    "Name":      ["Ravi", "Priya", "Arjun", "Meena", "Kiran"],
    "Maths":     [85, 92, 78, 95, 88]})
sem2df = pd.DataFrame({
    "Name":      ["Ravi", "Priya", "Arjun", "Meena", "Kiran"],
    "Maths":     [90, 88, 84, 97, 91]})
with pd.ExcelWriter("all_semesters.xlsx", engine="openpyxl") as writer:
    sem1df.to_excel(writer,sheet_name="Sem_1",index=False)
    sem2df.to_excel(writer,sheet_name="Sem_2",index=False)
print("---Semester 1---")
print(pd.read_excel("all_semesters.xlsx",sheet_name="Sem_1"))
print("---Semester 2---")
print(pd.read_excel("all_semesters.xlsx",sheet_name="Sem_2"))

---Semester 1---
    Name  Maths
0   Ravi     85
1  Priya     92
2  Arjun     78
3  Meena     95
4  Kiran     88
---Semester 2---
    Name  Maths
0   Ravi     90
1  Priya     88
2  Arjun     84
3  Meena     97
4  Kiran     91

In [8]:
''' 
Q20. End-to-end pipeline — read, process, save

Write a complete program that does the following in sequence:

a) Read students.csv (Name, RollNo, Maths, Physics, City).

b) Add a Total column (Maths + Physics).

c) Add an Average column (Total / 2, rounded to 1 decimal place).

d) Add a Result column: if Average > 80 then Pass, else Fail.

e) Save the full processed DataFrame to processed_results.csv without index.

f) From the saved file, read back only the students who Passed and print them.

g) Print how many students Passed and how many Failed.

Expected output:

# Passing students read back from file:
    Name  RollNo  Maths  Physics  Total  Average Result
0   Ravi     101     85       76    161     80.5   Pass
1  Priya     102     92       88    180     90.0   Pass
3  Meena     104     95       90    185     92.5   Pass
4  Kiran     105     88       79    167     83.5   Pass

Pass     4
Fail     1
Name: Result, dtype: int64


---

'''
print()

In [32]:
import numpy as np 
import pandas as pd  

df = pd.read_csv("student2.csv")
df["Total"] = df["Maths"] + df["Physics"] 
df["Average"] = round(df["Total"]/2,1)
df["Result"] = np.where(df["Average"]>80.0,"Pass","Fail")
df.to_csv("processed_results.csv",index=False) 
new_df = pd.read_csv("processed_results.csv")
print(new_df[new_df["Result"]=="Pass"])
p = sum( new_df["Result"]=="Pass" )
f = sum(new_df["Result"] == "Fail")
print("Pass  ",p)
print("Fail  ",f)

print(new_df["Result"].value_counts())

    Name  RollNo  Maths  Physics       City  Total  Average Result
0   Ravi     101     85       76  Hyderabad    161     80.5   Pass
1  Priya     102     92       88    Chennai    180     90.0   Pass
3  Meena     104     95       90  Hyderabad    185     92.5   Pass
4  Kiran     105     88       79       Pune    167     83.5   Pass
Pass   4
Fail   1
Result
Pass    4
Fail    1
Name: count, dtype: int64