In [22]:
import pandas as pd 
import numpy as np 
import random
random.seed(0)
days = ["mon","tue","wed","thur","fri","sat","sun"]
x = pd.Series( [np.round(np.random.random()*100, 2) for i in range(7)],index=days )
print(x)
mintemp = pd.Series([random.randint(5,35) for i in range(7)],index = days)
maxtemp = pd.Series([random.randint(mintemp[i],45) for i in range(7)],index = days)

print(mintemp)
print(maxtemp)
print()

mon     37.08
tue     14.24
wed     83.15
thur    52.30
fri     66.54
sat     69.03
sun     34.34
dtype: float64
mon     32
tue     17
wed     29
thur    33
fri     18
sat      6
sun     13
dtype: int64
mon     40
tue     32
wed     41
thur    45
fri     44
sat     25
sun     43
dtype: int64

thursday 33
Wetttest day wed 83.15
mon    100.0
dtype: float64

C:\Users\susha\AppData\Local\Temp\ipykernel_13260\1697506104.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  maxtemp = pd.Series([random.randint(mintemp[i],45) for i in range(7)],index = days)

In [33]:
print("thursday",mintemp["thur"])
print("Wetttest day",days[np.argmax(x)],np.max(x))
x["mon"]=100.0
print(x[x==100.0])
print(mintemp.idxmin())
print()
print("min temperature when rainfall was > 50")
print( mintemp[x>50] )
print()
print( maxtemp[x>50])

thursday 33
Wetttest day mon 100.0
mon    100.0
dtype: float64
sat

min temperature when rainfall was > 50
mon     32
wed     29
thur    33
fri     18
sat      6
dtype: int64

mon     40
wed     41
thur    45
fri     44
sat     25
dtype: int64

In [35]:
print( mintemp[x.idxmin()])
print( maxtemp[x.idxmin()])

17
32

In [36]:
print( maxtemp[x>50] )

mon     40
wed     41
thur    45
fri     44
sat     25
dtype: int64

In [37]:
# "what is standard variance? why will i use it and how and where "
# is std var and std dev same ? 
s = {1,2,3,4}
new = pd.Series(s)
new

TypeError: 'set' type is unordered

In [39]:
fruits = {"apple":"mon","mango":"tue"}
j = pd.DataFrame(fruits)
j

ValueError: If using all scalar values, you must pass an index

In [51]:
fruits = {"mon":["mango","tomato","chicken"],"tue":["watermelon","spinach","fish"],"wed":["grapes","capsicum","mutton"],"thur":["Cherry","beetroot","prawns"]}
j = pd.DataFrame(fruits, index=["fruits","vegetables","animals"] )
print(j)
print() 
print(j["mon"]["fruits"],"\n")
print(j["mon"],"\n")
print(j)

                mon         tue       wed      thur
fruits        mango  watermelon    grapes    Cherry
vegetables   tomato     spinach  capsicum  beetroot
animals     chicken        fish    mutton    prawns

mango

fruits          mango
vegetables     tomato
animals       chicken
Name: mon, dtype: object

In [52]:
j

                mon         tue       wed      thur
fruits        mango  watermelon    grapes    Cherry
vegetables   tomato     spinach  capsicum  beetroot
animals     chicken        fish    mutton    prawns

In [55]:
#j.loc[Row ,Col ]
j.loc["vegetables":,"wed":]

                 wed      thur
vegetables  capsicum  beetroot
animals       mutton    prawns

In [57]:
j["fri"] = ["guava","dal","pork"]
j

                mon         tue       wed      thur    fri
fruits        mango  watermelon    grapes    Cherry  guava
vegetables   tomato     spinach  capsicum  beetroot    dal
animals     chicken        fish    mutton    prawns   pork

In [58]:
j=j.drop(columns=["wed"])
j

                mon         tue      thur    fri
fruits        mango  watermelon    Cherry  guava
vegetables   tomato     spinach  beetroot    dal
animals     chicken        fish    prawns   pork