SyntaxError: Generator expression must be parenthesized (1289681668.py, line 4)

In [9]:
import pandas as pd 
import numpy as np 
import random
x = pd.Series([np.round(random.random()*100)] for _ in range(7),index=["mon","tue","wed","thur","fri","sat","sun"])

SyntaxError: Generator expression must be parenthesized (4250133047.py, line 4)

In [8]:
import pandas as pd 
df = pd.read_csv("student2.csv")
name_col = df.columns[0]
print(name_col)
subj_names = df.columns[1:]
print(subj_names)

for i,j in df.iterrows():
    # print(j) 
    print(j["Name"])
    print(j[subj_names])

Name
Index(['RollNo', 'Maths', 'Physics', 'City'], dtype='object')
Ravi
RollNo           101
Maths             85
Physics           76
City       Hyderabad
Name: 0, dtype: object
Priya
RollNo         102
Maths           92
Physics         88
City       Chennai
Name: 1, dtype: object
Arjun
RollNo           103
Maths             78
Physics           82
City       Bangalore
Name: 2, dtype: object
Meena
RollNo           104
Maths             95
Physics           90
City       Hyderabad
Name: 3, dtype: object
Kiran
RollNo      105
Maths        88
Physics      79
City       Pune
Name: 4, dtype: object

In [1]:
import pandas as pd 
df = pd.read_csv("Results.csv")
df.head()

    name  RollNo  Maths  Physics City  total
0   Ravi     101     85       76  hyd    161
1  Priya     102     92       88  chn    180
2  Arjun     103     78       82  blr    160
3  Meena     104     95       90  hyd    185
4  Kiran     105     88       79  pun    167

In [10]:
df.loc[3,"Maths"] = 100

In [11]:
df.head()

    name  RollNo  Maths  Physics City  total
0   Ravi     101     85       76  hyd    161
1  Priya     102     92       88  chn    180
2  Arjun     103     78       82  blr    160
3  Meena     104    100       90  hyd    185
4  Kiran     105     88       79  pun    167

In [13]:
df.iloc[3,2] = 99

In [14]:
df.head()

    name  RollNo  Maths  Physics City  total
0   Ravi     101     85       76  hyd    161
1  Priya     102     92       88  chn    180
2  Arjun     103     78       82  blr    160
3  Meena     104     99       90  hyd    185
4  Kiran     105     88       79  pun    167

In [21]:
df.index = df["name"]
df.drop(columns="name",inplace=True)

In [22]:
df.head()

       RollNo  Maths  Physics City  total
name
Ravi      101     85       76  hyd    161
Priya     102     92       88  chn    180
Arjun     103     78       82  blr    160
Meena     104     99       90  hyd    185
Kiran     105     88       79  pun    167

In [23]:
df["Maths"]["Meena"]

np.int64(99)